server:
  port: 9003
spring:
  application:
    name: hystrix-service-consumer-9003
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
    ####################配置具体方法超时时间 为 3 秒########################
    HystrixConsumerController#service_timeout(Integer):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

